# Generated by Django 4.1.6 on 2023-02-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_username', models.CharField(max_length=122)),
                ('f_pasword', models.CharField(max_length=122)),
            ],
        ),
    ]
