# Generated by Django 4.1.6 on 2023-02-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attandanceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersdb',
            old_name='f_pasword',
            new_name='f_password',
        ),
    ]
