# Generated by Django 4.1.6 on 2023-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attandanceapp', '0002_rename_f_pasword_usersdb_f_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersDb',
        ),
    ]
